MODEL:
  ARCHITECTURE: cqtnet
  CHECKPOINT_PATH: checkpoint/model_checkpoint.pth
  CONV_CHANNEL: 40
  DOWNSAMPLE_FACTOR: 20
  EMBEDDING_SIZE: 512
  L2_NORMALIZE: true
  NAME: Discogs-VINet-MIREX-full_set
  NORMALIZATION: bn
  POOLING: adaptive_max
  PROJECTION: linear
  SIMILARITY_SEARCH: MIPS
TRAIN:
  CONTEXT_LENGTH: 7600
